---
name: Release

on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install latest Helm
        uses: azure/setup-helm@v4

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./gh-pages/

      - name: Deploy Helm charts
        run: |
          shopt -s failglob
          cp -f ./capone-*-${GITHUB_REF_NAME:1}.tgz ./gh-pages/charts/

      - name: Re-index Helm repos
        run: |
          helm repo index ./ --url https://sk4zuzu.github.io/gaga/charts/
        working-directory: ./gh-pages/charts/

      - name: Push gh-pages
        run: |
          shopt -s failglob
          git add ./index.yaml ./capone-*-${GITHUB_REF_NAME:1}.tgz
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -m "${GITHUB_REF_NAME:1}"
          git push
        working-directory: ./gh-pages/charts/
