---
name: Release

on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build and push images
        run: make buildx _TAG="ghcr.io/${GITHUB_REPOSITORY,,}:$GITHUB_REF_NAME" BUILDX_NO_DEFAULT_ATTESTATIONS=1

      - name: Tag and push image (latest)
        run: |
          docker pull "ghcr.io/${GITHUB_REPOSITORY,,}:$GITHUB_REF_NAME"
          docker tag "ghcr.io/${GITHUB_REPOSITORY,,}:$GITHUB_REF_NAME" "ghcr.io/${GITHUB_REPOSITORY,,}:latest"
          docker push "ghcr.io/${GITHUB_REPOSITORY,,}:latest"

#      - name: Checkout repository
#        uses: actions/checkout@v4
#        with:
#          ref: gh-pages
#          path: ./gh-pages/
#
#      - name: Install latest Helm
#        uses: azure/setup-helm@v4
#
#      - name: Deploy Helm charts
#        run: |
#          shopt -s failglob
#          cp -f ./capone-*-${GITHUB_REF_NAME:1}.tgz ./gh-pages/charts/
#
#      - name: Re-index Helm repos
#        run: |
#          helm repo index ./ --url https://sk4zuzu.github.io/gaga/charts/
#        working-directory: ./gh-pages/charts/
#
#      - name: Push gh-pages
#        run: |
#          shopt -s failglob
#          git add ./index.yaml ./capone-*-${GITHUB_REF_NAME:1}.tgz
#          git config user.name "$GITHUB_ACTOR"
#          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
#          git commit -m "${GITHUB_REF_NAME:1}"
#          git push
#        working-directory: ./gh-pages/charts/
